// modules/solid/src/entry-server.tsx
import { renderToStream } from "solid-js/web";
import App from "./App";
import { IncomingMessage, ServerResponse } from "http";

export async function buildHandler() {
  return async function handler(_: IncomingMessage, res: ServerResponse) {
    const stream = renderToStream(() => <App />);
    res.setHeader("content-type", "text/html");
    stream.pipe(res);
  };
}

// modules/mfng/src/entry-server.tsx
import { createRscAppStream } from "@mfng/core/server/rsc";
import { createHtmlStream } from "@mfng/core/server/ssr";
import { IncomingMessage, ServerResponse } from "http";
import * as React from "react";
import { Readable } from "stream";
import { ReadableStream } from "stream/web";
import { Page } from "./page";

export async function buildHandler() {
  return async function handler(_: IncomingMessage, res: ServerResponse) {
    const rscAppStream = createRscAppStream(<Page />, {
      reactClientManifest: {},
    });

    const htmlStream = await createHtmlStream(rscAppStream, {
      reactSsrManifest: {},
    });

    res.setHeader("content-type", "text/html; charset=utf-8");
    Readable.fromWeb(htmlStream as ReadableStream<Uint8Array>).pipe(res);
  };
}
