// modules/solid/src/App.tsx
import { For, Suspense, createResource } from "solid-js";
import { testData } from "testdata";

function App() {
  return (
    <Suspense>
      <Table />
    </Suspense>
  );
}

function Table() {
  const [tdata] = createResource(testData);

  return (
    <table>
      <tbody>
        <For each={tdata()}>{(entry) => <Entry entry={entry} />}</For>
      </tbody>
    </table>
  );
}

function Entry(props: { entry: { id: string; name: string } }) {
  return (
    <tr>
      <td>{props.entry.id}</td>
      <td>{props.entry.name}</td>
    </tr>
  );
}

export default App;

// modules/preact/src/App.tsx
import { testData } from "testdata";

type Entry = { id: string, name: string };

function Table(props: { data: Entry[] }) {
  return (
    <table>
      <tbody>
        {props.data.map((entry: Entry) => (
          <Entry
            key={entry.id}
            entry={entry}
          />
        ))}
      </tbody>
    </table>
  );
}

function Entry(props: { entry: Entry }) {
  return (
    <tr>
      <td>{props.entry.id}</td>
      <td>{props.entry.name}</td>
    </tr>
  );
}

export async function App() {
  const tdata = await testData();

  return <Table data={tdata} />;
}
