// modules/hono/src/App.tsx
import { testData } from 'testdata'

function App() {
  return <Table data={testData()} />
}

async function Table({ data }: { data: ReturnType<typeof testData> }) {
  const tdata = await data
  return (
    <table>
      <tbody>
        {tdata.map((entry) => (
          <Entry entry={entry} />
        ))}
      </tbody>
    </table>
  )
}

function Entry(props: { entry: { id: string; name: string } }) {
  return (
    <tr>
      <td>{props.entry.id}</td>
      <td>{props.entry.name}</td>
    </tr>
  )
}

export default App

// modules/solid/src/App.tsx
import { For, Suspense, createResource } from "solid-js";
import { testData } from "testdata";

function App() {
  return (
    <Suspense>
      <Table />
    </Suspense>
  );
}

function Table() {
  const [tdata] = createResource(testData);

  return (
    <table>
      <tbody>
        <For each={tdata()}>{(entry) => <Entry entry={entry} />}</For>
      </tbody>
    </table>
  );
}

function Entry(props: { entry: { id: string; name: string } }) {
  return (
    <tr>
      <td>{props.entry.id}</td>
      <td>{props.entry.name}</td>
    </tr>
  );
}

export default App;
